fortune:
  fallbackFortune: Your future is bright! 
  fortuneServiceURL: http://fortune-service
  
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
